name: SAST - SonarQube Cloud

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  sonar:
    name: Analyse SAST SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le dépôt
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Installer Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Installer les dépendances
        run: npm ci

      - name: Lancer les tests avec couverture LCOV
        run: |
          npm run test:coverage -- \
            --coverage-reporters=text \
            --coverage-reporters=lcov

      - name: Vérifier le rapport LCOV
        run: test -f coverage/azure-quiz-frontend/lcov.info

      - name: Analyse SonarQube Cloud
        uses: SonarSource/sonarqube-scan-action@c7ee0f9df90b7aa20e8dcf9695dcfe2e7da5b4f2 # v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=a-benslimane
            -Dsonar.projectKey=A-benslimane_bilan-azure-quiz-frontend
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.javascript.lcov.reportPaths=coverage/azure-quiz-frontend/lcov.info

      - name: Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@7a5fffe8e523c40e0c740b6bc2712ab503e52efa # v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
